language: python
if: branch = master or tag IS present
python: 3.7
dist: bionic
services:
    - docker

before_script:
    # authorization
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$QUAY_PASSWORD" | docker login -u "$QUAY_USERNAME" --password-stdin quay.io
    - sudo chmod 777 /home/travis/.docker/config.json

script:
    # RiotKit Do is installed by Travis from requirements.txt file
    - cp .env.dist .env
    - rkd :build-all-versions --commit-msg="$TRAVIS_COMMIT_MESSAGE"
