language: python
if: branch = master or tag IS present
python: 3.6
services:
    - docker

before_script:
    # authorization
    - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "$QUAY_PASSWORD" | sudo docker login -u "$QUAY_USERNAME" --password-stdin quay.io
    - sudo chmod 777 /home/travis/.docker/config.json

script:
    - rkd :build-all-versions --commit-msg="$TRAVIS_COMMIT_MESSAGE"
