version: '2'

volumes:
    postgres:
    media:

services:
    taiga:
        image: quay.io/riotkit/taiga:${VERSION}
        ports:
            - 80:80
        depends_on:
            - postgres
        volumes:
            # all data placed in volumes are kept between container updates/deletion/recreation
            - media:/usr/src/taiga-back/media
        env_file:
            - .env

    postgres:
        image: postgres
        environment:
            POSTGRES_DB: ${TAIGA_DB_NAME}
            POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
            POSTGRES_USER: ${TAIGA_DB_USER}
        ports:
            - 5432
        volumes:
            - postgres:/var/lib/postgresql/data
